import "./globals.css";

export const metadata = {
  title: "The Element at Sobha One | Premium 2 Bedroom Apartment",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png"
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
